apiVersion: 1

datasources:
  - name: DuckDB
    type: marcusolsson-duckdb-datasource
    uid: DUCKDB_LOCAL
    access: proxy
    jsonData:
      path: /var/lib/grafana/duckdb/personal_finance.duckdb
    editable: true
