apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: dagster_postgres:5432
    database: personal_finance
    user: grafanareader
    secureJsonData:
      password: ${GRAFANA_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false
    isDefault: true
    editable: true