apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: PCC52D03280B7034C
    url: 192.168.1.103:5432
    user: grafanareader
    secureJsonData:
      password: $GRAFANA_PASSWORD
    jsonData:
      database: personal_finance
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false
    isDefault: true
    editable: true